name: final_ecommerce
description: ecommerce app user app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  carousel_pro_nullsafety: ^1.0.2
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  firebase_core: ^2.7.0
  google_sign_in: 6.0.2
  shared_preferences: ^2.0.18
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  image_picker: ^0.8.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  # example:
  fonts:
    - family: signatra
      fonts:
        - asset: assets/fonts/signatra.ttf
